### PR TITLE
Fix #759 for Print Code button in Two-step Login

### LINKED ISSUE #759: Print Code button for recovery code does not work
## Steps To Reproduce

1. Go to https://vault.bitwarden.com/#/settings/two-factor
2. Register one of the Two-step login methods
3. Click on 'View recovery code'
4. Click on 'Print Code'

## Expected Result

A PDF or some kind of backup code in the file is downloaded 

## Actual Result

Another tab opened then disappeared quickly. Nothing is downloaded or copied!

## Screenshots or Videos

image

## Environment

- Operating system: Windows 10
- Browser: Chrome 87.0.4280.88
- Build Version (Bottom of the page): 2.17.1

## Additional Context

Register a two-step login method

### PR DESCRIPTION
**Pull request by hckhanh**
As I described in the issue #759, the `Print Code` button did not work correctly.
My PR will make sure the window will open up then close after the Code is printed completely.

Happy New Year 🎉🎉🎉

### CODE REVIEW

File: src/app/settings/two-factor-recovery.component.ts [hunk 1]
```diff
@@ -30,8 +30,8 @@ export class TwoFactorRecoveryComponent {
             '<code style="font-family: Menlo, Monaco, Consolas, \'Courier New\', monospace;">' +
             this.code + '</code></div>' +
             '<p style="text-align: center;">' + new Date() + '</p>');
+        w.onafterprint = w.close;
```
Comment (cscharf) [inline src/app/settings/two-factor-recovery.component.ts:33]: Awesome, thanks! Can you please change this to it's own enclosure, `() => w.close();` to ensure context is maintained?

Comment (hckhanh) [reply src/app/settings/two-factor-recovery.component.ts]: @cscharf thank you for your feedback

**Review by cscharf — APPROVED** [review]
